server:
  port: 8092

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: service-product
        uri: lb://service-product
        predicates:
          - Path=/products/**
        filters:
          - name: Circuitbreaker
            args:
              name: products
              statusCodes: 500
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8091/eureka/
