server:
  port: 8092

#defecto (nombre de la configuracion del circuibraker)
#sliding-window-size (tamaño de la ventana deslizante)
#failure-rate-threshold (taza de fallas de un umbral)
#wait-duration-in-open-state (tiempo de espera estado abierto)
#permitted-number-of-calls-in-half-open-state (cantidad de llamda permitida estado semi-abierto)
#slow-call-rate-threshold (tasa llamada lentas)
#slow-call-duration-threshold (tiempo de duracion de la llamada lenta)
#items (atributo/ nombre circuitbreaker para usarlos en anotaciones)
#base-config (asignamos la configuracion "defecto")
#timeout-duration (configuracion del timeout 2s)

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
    instances:
      products:
        base-config: default
  timelimiter:
    configs:
      default:
        timeout-duration: 2s
    instances:
      products:
        base-config: default

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: service-product
        uri: lb://service-product
        predicates:
          - Path=/products/**
        filters:
          - name: Circuitbreaker
            args:
              name: products
              statusCodes: 500
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8091/eureka/
